### PR TITLE
Support a custom timestamp format in yaml frontmatter on posts

### PR DESCRIPTION
**Pull request by alzeih**
Using `--timestamp-format "%Y-%m-%d %H:%M %z"` the commands `jekyll post` and `jekyll publish` can have a user specified format to give to `strftime` for the yaml frontmatter on posts.

If not specified, the default format is used.

### CODE REVIEW

**Comment by mattr-** [comment]
I like this idea. Could you update the PR to remove the conflicts? Once that's done, I'll give it a proper review.

**Comment by alzeih** [comment]
I have documented `--timestamp-format` in `README.md` for the post and publish commands using an example format `"%Y-%m-%d %H:%M:%S %z` that differs from the default at `Jekyll::Compose::DEFAULT_TIMESTAMP_FORMAT`.

**Comment by alzeih** [comment]
Please hold this PR open until after #103 has been resolved, as `jekyll compose` will need to support this too if accepted.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
