### PR TITLE
Depend on jekyll at least of version 2.5.0

### LINKED ISSUE #28: Command not available; unresolved specs
```sh
$ bundle exec jekyll post
Invalid command. Use --help for more information 

$ jekyll post
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      listen (~> 2.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/bin/jekyll:23:in `load'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/bin/jekyll:23:in `<main>’
```

I’ve tried both using `jekyll-compose` in my Gemfile as well as a gem in `_config.yml` with the same result.

### PR DESCRIPTION
**Pull request by exalted**
Close #28

### CODE REVIEW

**Comment by exalted** [comment]
I am not sure how to deal with travis (there are references to `JEKYLL_VERSION` in there), if/how to “bump up” the `jekyll-compose` version or update rubygems.org.

/cc @parkr

**Comment by parkr** [comment]
> I am not sure how to deal with travis

Where it says `JEKYLL_VERSION=2.0`, make that `JEKYLL_VERSION=2.5`. Thanks!

**Comment by exalted** [comment]
@parkr apparently it’s :white_check_mark:

**Comment by exalted** [comment]
🎉🙇


--
Ali

**Comment by parkr** [comment]
Thanks for the pull, @exalted!

**Comment by exalted** [comment]
Sure thing! Cheers.


--
Ali

**Pull request merged**
