### PR TITLE
Add/Remove Dates When Publishing/Unpublishing

### PR DESCRIPTION
**Pull request by gavinhoward**
This PR solves #55 and replaces #63.

Comments and review appreciated; I am new to Ruby.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@gavinhoward Principle-wise, I'm entirely against this pull request.
You simply pulled in changes from #63, made a very minor edit and recommitted everything under your name. *That is just wrong!*

What you should've done is **`cherry-pick`** the previous author's commit and *`amend`* it by making necessary changes and [listing yourselves as a **`Co-author`**](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors)
(You can still do it on this very branch with some adept Git skills though..)

Moving forward, here are some additional FYIs:
  - The original pull request lacked tests and were requested for, by the maintainers. (Which you [seemed to agree](https://github.com/jekyll/jekyll-compose/pull/63#issuecomment-478306997) to provide..) Where are the tests in this pull request..??
  - The changes feel like there're some RuboCop offenses present. Please run our linter script `script/fmt` to detect any linting lapses and consequently correct any offenses automatically with `script/fmt -a` and with some manual editing.
  - When creating a pull request that closes an issue and/or another pull request, please [use appropriate keywords](https://help.github.com/en/articles/closing-issues-using-keywords)

*Apologies, if my comments above seemed harsh and unfriendly.
Moreover, i appreciate you taking the time and effort to bring a stale proposal towards the finish line.*

**Comment by gavinhoward** [comment]
> @gavinhoward Principle-wise, I'm entirely against this pull request.
> You simply pulled in changes from #63, made a very minor edit and recommitted everything under your name. _That is just wrong!_

I did not know how else to do it.

> What you should've done is **`cherry-pick`** the previous author's commit and _`amend`_ it by making necessary changes and [listing yourselves as a **`Co-author`**](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors)
> (You can still do it on this very branch with some adept Git skills though..)

I did not know that you could list coauthors; I would have if I did. I did list the place where I got the code in the commit message.

> Moving forward, here are some additional FYIs:
> 
> * The original pull request lacked tests and were requested for, by the maintainers. (Which you [seemed to agree](https://github.com/jekyll/jekyll-compose/pull/63#issuecomment-478306997) to provide..) Where are the tests in this pull request..??

I am new to Ruby and could not figure out where the tests were.

> * The changes feel like there're some RuboCop offenses present. Please run our linter script `script/fmt` to detect any linting lapses and consequently correct any offenses automatically with `script/fmt -a` and with some manual editing.

I did not know about RuboCop. I am new to Ruby.

> * When creating a pull request that closes an issue and/or another pull request, please [use appropriate keywords](https://help.github.com/en/articles/closing-issues-using-keywords)

I didn't know about keywords.

> _Apologies, if my comments above seemed harsh and unfriendly. Moreover, i appreciate you taking the time and effort to bring a stale proposal towards the finish line._

You have an interesting way of showing it. I do not feel appreciated. Telling me that something I did was "just wrong", with _emphasis_, made it clear where you stood, never mind that I didn't even know that I could list a coauthor. Please don't assume.

I am going to close this PR. _If_ I try again, I should just restart.

**Comment by ashmaroli** [comment]
@gavinhoward I accept my mistake. Apologies, once again.
I'll add a couple of those instructions to this project's README.

Hope to see you again..

**Comment by gavinhoward** [comment]
I appreciate the apology. That is something rare and nice these days.

Just one question: where are the tests? My best guess is in the `spec/` directory, but I am not sure.

**Comment by ashmaroli** [comment]
Yes, the tests are in the `spec/` directory. The tests are based on [RSpec](https://rspec.info).

**Comment by gavinhoward** [comment]
Okay. I will see what I can do.

**Pull request closed without merging**
