### PR TITLE
Add rename command to change titles and filenames

### LINKED ISSUE #97: Rename command
At least for me, writing a title is the last step of the writing process. I start by having some idea of what I want to write but it always evolves over the course of actual writing. If I start by writing a title first, more often than not, I need to amend that title. In jekyll that means I need to change front matter and rename a file. Not the nicest IMO.

I'd like to be able to do something like `jekyll rename _drafts/untitled.md 'My Actual Title'`

When looking through the source code to see how this might be accomplished, I noticed that `Jekyll::Compose::ArgParser#validate!` returns a hard-coded error message if the argument list is empty, which complains that a name must be specified. Which is, of course, wouldn't work with a command that requires two arguments like a rename command. 

Do you think a rename command is worthwhile? If so, how would you handle the hard-coded error message?

Thanks.

### PR DESCRIPTION
**Pull request by alzeih**
`jekyll rename _drafts/my-old-draft.md "My New Draft"` will

- move the draft to _drafts/my-new-draft.md
- set the yaml front matter title attribute to "My New Draft"

`jekyll rename _drafts/my-old-draft.md "My New Draft" --date "2012-03-04"` will

- move the draft to _drafts/my-new-draft.md
- set the yaml front matter title attribute to "My New Draft"
- set the yaml front matter date to 2012-03-04

`jekyll rename _posts/2001-02-03-my-old-post.md "My New Post"` will

- move the post to _posts/2001-02-03-my-new-post.md
- set the yaml front matter title attribute to "My New Post"

`jekyll rename _posts/2001-02-03-my-old-post.md "My New Post" --date "2012-03-04"` will

- move the post to _posts/2012-03-04-my-new-post.md
- set the yaml front matter title attribute to "My New Post"
- set the yaml front matter date to 2012-03-04

`jekyll rename _posts/2001-02-03-my-old-post.md "My New Post" --now` will

- move the post to _posts/[now]-my-new-post.md
- set the yaml front matter title attribute to "My New Post"
- set the yaml front matter date to [now]

Closes #97 by @imabusabah.

### CODE REVIEW

**Comment by alzeih** [comment]
I have added documentation to `README.md` and tests for the `rename` command.

**Comment by alzeih** [comment]
This PR is related to #97 by @imabusabah. Sorry for not mentioning this earlier!

**Comment by alzeih** [comment]
At the moment this only works for drafts. Should this also work for posts?

**Comment by alzeih** [comment]
So, this PR will now rename posts and drafts.

Renaming posts raises a question of what to do with the post date in the filename and the front matter, as these two values may not exist, or not be the same date, or not be on the same date depending on the timezone.

Right now, everything that gets renamed will also update the date in the front matter and (posts only) the date in the filename. This has the advantage of making sure the post date in the filename and the date in the front matter will match. This has the disadvantage of `jekyll rename` also changing the date in the front matter and (posts only) the filename, which is perhaps an unexpected side effect of a rename.

A flag for `--no-yaml-date-update` or `--yaml-date-update` or something like that would be possible, but then what about the filename? The datestamp would need to be parsed out of the filename and written back as is? Should rename make the filename match the existing front matter, or vice versa? What should it do by default? What do people expect rename to do without knowing how it works?

I guess having `jekyll publish` using now as a default is helpful, but that makes sense to me for publish. I'm not sure it makes sense for `jekyll rename`.

**Comment by DirtyF** [comment]
I feel like rename shouldn't change date by default — only if `--date` option is passed eventually, with default being to now.

```
jekyll rename _drafts/my-old-draft.md
jekyll rename _drafts/my-old-draft.md --date
jekyll rename _drafts/my-old-draft.md --date "2004-05-06"

**Comment by ashmaroli** [comment]
@alzeih What is motive behind having `RenameArgParser` and `RenamingArgParser` as separate classes? (not readily apparent). IMO, one class from merging the two should suffice..

**Comment by alzeih** [comment]
> @alzeih What is motive behind having `RenameArgParser` and `RenamingArgParser` as separate classes? (not readily apparent). IMO, one class from merging the two should suffice..

Just remainders from using another command as a template, so `RenamingArgParser` has now gone.

**Comment by alzeih** [comment]
> I feel like rename shouldn't change date by default — only if `--date` option is passed eventually, with default being to now.
> 
> ```
> jekyll rename _drafts/my-old-draft.md
> jekyll rename _drafts/my-old-draft.md --date (or --now)
> jekyll rename _drafts/my-old-draft.md --date "2004-05-06"
> ```

```
$ jekyll rename _posts/2019-09-08-a-new-post.md "A New Title" --date
bundler: failed to load command: jekyll (.../.gem/bin/jekyll)
OptionParser::MissingArgument: missing argument: --date
  .../.gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:31:in `go'
  .../.gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  .../.gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  .../.gem/bin/jekyll:23:in `load'
  .../.gem/bin/jekyll:23:in `<top (required)>'
```

Looks like `--now` it is then!

**Comment by ashmaroli** [comment]
@alzeih Can you amend the commit message to a meaningful sentence less than 50 chars..?
Like perhaps `Add support for renaming documents`..
`Renaming documents` just doesn't cut it.

**Comment by alzeih** [comment]
> @alzeih Can you amend the commit message to a meaningful sentence less than 50 chars..?
> Like perhaps `Add support for renaming documents`..
> `Renaming documents` just doesn't cut it.

Done (49 chars).

Also changed:

```diff
diff --git a/lib/jekyll/commands/rename.rb b/lib/jekyll/commands/rename.rb
index 9ef6836..92ccf38 100644
--- a/lib/jekyll/commands/rename.rb
+++ b/lib/jekyll/commands/rename.rb
@@ -119,9 +119,9 @@ module Jekyll
 
       def to
         if @params.post?
-          "#{@params.dirname}/#{_date_stamp}-#{file_name}"
+          File.join(@params.dirname, "#{_date_stamp}-#{file_name}")
         else
-          "#{@params.dirname}/#{file_name}"
+          File.join(@params.dirname, file_name)
         end
       end
```

**Comment by alzeih** [comment]
This PR is waiting for review. Is there anything I should have done so it is ready for review?

**Comment by ashmaroli** [comment]
@alzeih I have pushed the changes that I felt were needed. Now, it's upto the other members of the @jekyll/plugin-core to review the *combined* changes.

Please be patient.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
